### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by nbuhay** [michaelamartin/Introduction-to-Java-Programing-by-David-Liang#1]
?

**Comment by michaelamartin** [comment]
Copy whichever .java file you wish to test and run with an IDE such as NetBeans.  You can also compile a .java file by using the command line. See the following link: http://stackoverflow.com/questions/16137713/how-to-run-a-java-program-from-the-command-line

**Comment by nbuhay** [comment]
It worked - cheers!
